project:
  type: website
  output-dir: docs

website:
  title: "limruiwen.github.io"
  navbar:
    left:
      - href: Home.qmd
        text: Home
      - Analysis.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    include-css: /Users/limruiwen/Desktop/NM2207/limruiwen.github.io


editor: visual

