project:
  type: website
  output-dir: docs

website:
  title: "Rui Wen's Website"
  navbar:
    left:
      - href: Home.qmd
        text: "Home"
      - href: PR.qmd
        text: "Project Runover"
      - href: Analysis.qmd
        text: "Analysis"
    
format:
  html:
    theme: litera
    css: styles.css
    toc: true
    include-css: /Users/limruiwen/Desktop/NM2207/limruiwen.github.io


editor: visual

